In [1]:
from google.colab import drive, files
from sklearn.utils import shuffle
import seaborn as sns
import pandas as pd
import numpy as np
import gc
import os

drive.mount("/content/drive", force_remount = True)
path = "/content/drive/My Drive/TCC/Dataset"
if os.path.isdir(path):
  print("\nConteúdo da pasta:\n")
  !ls "{path}"

Mounted at /content/drive

Conteúdo da pasta:

ARP_Spoofing_train.pcap.csv		TCP_IP-DDoS-TCP4_train.pcap.csv
Benign_train.pcap.csv			TCP_IP-DDoS-UDP1_train.pcap.csv
MQTT-DDoS-Connect_Flood_train.pcap.csv	TCP_IP-DDoS-UDP2_train.pcap.csv
MQTT-DDoS-Publish_Flood_train.pcap.csv	TCP_IP-DDoS-UDP3_train.pcap.csv
MQTT-DoS-Connect_Flood_train.pcap.csv	TCP_IP-DDoS-UDP4_train.pcap.csv
MQTT-DoS-Publish_Flood_train.pcap.csv	TCP_IP-DDoS-UDP5_train.pcap.csv
MQTT-Malformed_Data_train.pcap.csv	TCP_IP-DDoS-UDP6_train.pcap.csv
Recon-OS_Scan_train.pcap.csv		TCP_IP-DDoS-UDP7_train.pcap.csv
Recon-Ping_Sweep_train.pcap.csv		TCP_IP-DDoS-UDP8_train.pcap.csv
Recon-Port_Scan_train.pcap.csv		TCP_IP-DoS-ICMP1_train.pcap.csv
Recon-VulScan_train.pcap.csv		TCP_IP-DoS-ICMP2_train.pcap.csv
TCP_IP-DDoS-ICMP1_train.pcap.csv	TCP_IP-DoS-ICMP3_train.pcap.csv
TCP_IP-DDoS-ICMP2_train.pcap.csv	TCP_IP-DoS-ICMP4_train.pcap.csv
TCP_IP-DDoS-ICMP3_train.pcap.csv	TCP_IP-DoS-SYN1_train.pcap.csv
TCP_IP-DDoS-ICMP4_train.pcap.csv	TCP_IP-DoS-SYN2_train.pcap.csv
TCP_IP-DDoS-ICMP5_train.pcap.csv	TCP_IP-DoS-SYN3_train.pcap.csv
TCP_IP-DDoS-ICMP6_train.pcap.csv	TCP_IP-DoS-SYN4_train.pcap.csv
TCP_IP-DDoS-ICMP7_train.pcap.csv	TCP_IP-DoS-TCP1_train.pcap.csv
TCP_IP-DDoS-ICMP8_train.pcap.csv	TCP_IP-DoS-TCP2_train.pcap.csv
TCP_IP-DDoS-SYN1_train.pcap.csv		TCP_IP-DoS-TCP3_train.pcap.csv
TCP_IP-DDoS-SYN2_train.pcap.csv		TCP_IP-DoS-TCP4_train.pcap.csv
TCP_IP-DDoS-SYN3_train.pcap.csv		TCP_IP-DoS-UDP1_train.pcap.csv
TCP_IP-DDoS-SYN4_train.pcap.csv		TCP_IP-DoS-UDP2_train.pcap.csv
TCP_IP-DDoS-TCP1_train.pcap.csv		TCP_IP-DoS-UDP3_train.pcap.csv
TCP_IP-DDoS-TCP2_train.pcap.csv		TCP_IP-DoS-UDP4_train.pcap.csv
TCP_IP-DDoS-TCP3_train.pcap.csv

Categorização em ataques

1. Categoria: MQTT Attack (IOT)

Ataques que exploram o protocolo MQTT, amplamente usado em dispositivos IoT. Incluem floods de conexão/publicação e injeção de pacotes malformados, visando exaustão de recursos, indisponibilidade do serviço e possíveis falhas de segurança em brokers e dispositivos conectados.

2. Categoria: Reconnaissance (Scanning)

Atividades de coleta de informações sobre a rede ou dispositivos, como varredura de portas, sistemas operacionais e vulnerabilidades. Geralmente são etapas iniciais de ataques, usadas para mapear alvos antes da exploração efetiva.

3. Categoria: DDoS

4. Categoria DoS

In [ ]:
# --- Tráfego Benigno ---
benign_df = pd.read_csv(f"{path}/Benign_train.pcap.csv")
# --- Ataques ARP ---
arp_spoofing_df = pd.read_csv(f"{path}/ARP_Spoofing_train.pcap.csv")
# --- Ataques MQTT ---
mqtt_ddos_connect_flood_df = pd.read_csv(f"{path}/MQTT-DDoS-Connect_Flood_train.pcap.csv")
mqtt_ddos_publish_flood_df = pd.read_csv(f"{path}/MQTT-DDoS-Publish_Flood_train.pcap.csv")
mqtt_dos_connect_flood_df = pd.read_csv(f"{path}/MQTT-DoS-Connect_Flood_train.pcap.csv")
mqtt_dos_publish_flood_df = pd.read_csv(f"{path}/MQTT-DoS-Publish_Flood_train.pcap.csv")
mqtt_malformed_data_df = pd.read_csv(f"{path}/MQTT-Malformed_Data_train.pcap.csv")
# --- Ataques de Reconhecimento (Recon) ---
recon_os_scan_df = pd.read_csv(f"{path}/Recon-OS_Scan_train.pcap.csv")
recon_ping_sweep_df = pd.read_csv(f"{path}/Recon-Ping_Sweep_train.pcap.csv")
recon_port_scan_df = pd.read_csv(f"{path}/Recon-Port_Scan_train.pcap.csv")
recon_vulscan_df = pd.read_csv(f"{path}/Recon-VulScan_train.pcap.csv")
# --- Ataques DDoS ---
tcp_ip_ddos_icmp1_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP1_train.pcap.csv")
tcp_ip_ddos_icmp2_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP2_train.pcap.csv")
tcp_ip_ddos_icmp3_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP3_train.pcap.csv")
tcp_ip_ddos_icmp4_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP4_train.pcap.csv")
tcp_ip_ddos_icmp5_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP5_train.pcap.csv")
tcp_ip_ddos_icmp6_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP6_train.pcap.csv")
tcp_ip_ddos_icmp7_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP7_train.pcap.csv")
tcp_ip_ddos_icmp8_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP8_train.pcap.csv")
tcp_ip_ddos_syn1_df = pd.read_csv(f"{path}/TCP_IP-DDoS-SYN1_train.pcap.csv")
tcp_ip_ddos_syn2_df = pd.read_csv(f"{path}/TCP_IP-DDoS-SYN2_train.pcap.csv")
tcp_ip_ddos_syn3_df = pd.read_csv(f"{path}/TCP_IP-DDoS-SYN3_train.pcap.csv")
tcp_ip_ddos_syn4_df = pd.read_csv(f"{path}/TCP_IP-DDoS-SYN4_train.pcap.csv")
tcp_ip_ddos_tcp1_df = pd.read_csv(f"{path}/TCP_IP-DDoS-TCP1_train.pcap.csv")
tcp_ip_ddos_tcp2_df = pd.read_csv(f"{path}/TCP_IP-DDoS-TCP2_train.pcap.csv")
tcp_ip_ddos_tcp3_df = pd.read_csv(f"{path}/TCP_IP-DDoS-TCP3_train.pcap.csv")
tcp_ip_ddos_tcp4_df = pd.read_csv(f"{path}/TCP_IP-DDoS-TCP4_train.pcap.csv")
tcp_ip_ddos_udp1_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP1_train.pcap.csv")
tcp_ip_ddos_udp2_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP2_train.pcap.csv")
tcp_ip_ddos_udp3_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP3_train.pcap.csv")
tcp_ip_ddos_udp4_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP4_train.pcap.csv")
tcp_ip_ddos_udp5_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP5_train.pcap.csv")
tcp_ip_ddos_udp6_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP6_train.pcap.csv")
tcp_ip_ddos_udp7_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP7_train.pcap.csv")
tcp_ip_ddos_udp8_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP8_train.pcap.csv")
# --- Ataques DoS ---
tcp_ip_dos_icmp1_df = pd.read_csv(f"{path}/TCP_IP-DoS-ICMP1_train.pcap.csv")
tcp_ip_dos_icmp2_df = pd.read_csv(f"{path}/TCP_IP-DoS-ICMP2_train.pcap.csv")
tcp_ip_dos_icmp3_df = pd.read_csv(f"{path}/TCP_IP-DoS-ICMP3_train.pcap.csv")
tcp_ip_dos_icmp4_df = pd.read_csv(f"{path}/TCP_IP-DoS-ICMP4_train.pcap.csv")
tcp_ip_dos_syn1_df = pd.read_csv(f"{path}/TCP_IP-DoS-SYN1_train.pcap.csv")
tcp_ip_dos_syn2_df = pd.read_csv(f"{path}/TCP_IP-DoS-SYN2_train.pcap.csv")
tcp_ip_dos_syn3_df = pd.read_csv(f"{path}/TCP_IP-DoS-SYN3_train.pcap.csv")
tcp_ip_dos_syn4_df = pd.read_csv(f"{path}/TCP_IP-DoS-SYN4_train.pcap.csv")
tcp_ip_dos_tcp1_df = pd.read_csv(f"{path}/TCP_IP-DoS-TCP1_train.pcap.csv")
tcp_ip_dos_tcp2_df = pd.read_csv(f"{path}/TCP_IP-DoS-TCP2_train.pcap.csv")
tcp_ip_dos_tcp3_df = pd.read_csv(f"{path}/TCP_IP-DoS-TCP3_train.pcap.csv")
tcp_ip_dos_tcp4_df = pd.read_csv(f"{path}/TCP_IP-DoS-TCP4_train.pcap.csv")
tcp_ip_dos_udp1_df = pd.read_csv(f"{path}/TCP_IP-DoS-UDP1_train.pcap.csv")
tcp_ip_dos_udp2_df = pd.read_csv(f"{path}/TCP_IP-DoS-UDP2_train.pcap.csv")
tcp_ip_dos_udp3_df = pd.read_csv(f"{path}/TCP_IP-DoS-UDP3_train.pcap.csv")
tcp_ip_dos_udp4_df = pd.read_csv(f"{path}/TCP_IP-DoS-UDP4_train.pcap.csv")

list_mqtt_dfs = [
    mqtt_ddos_connect_flood_df,
    mqtt_ddos_publish_flood_df,
    mqtt_dos_connect_flood_df,
    mqtt_dos_publish_flood_df,
    mqtt_malformed_data_df
    ]
mqtt_df = pd.concat(list_mqtt_dfs, ignore_index = True)

list_recon_dfs = [
    recon_os_scan_df, recon_ping_sweep_df, recon_port_scan_df, recon_vulscan_df
]
recon_df = pd.concat(list_recon_dfs, ignore_index = True)

list_ddos_dfs = [
    tcp_ip_ddos_icmp1_df, tcp_ip_ddos_icmp2_df, tcp_ip_ddos_icmp3_df, tcp_ip_ddos_icmp4_df, tcp_ip_ddos_icmp5_df, tcp_ip_ddos_icmp6_df, tcp_ip_ddos_icmp7_df, tcp_ip_ddos_icmp8_df,
    tcp_ip_ddos_syn1_df, tcp_ip_ddos_syn2_df, tcp_ip_ddos_syn3_df, tcp_ip_ddos_syn4_df, tcp_ip_ddos_tcp1_df, tcp_ip_ddos_tcp2_df, tcp_ip_ddos_tcp3_df, tcp_ip_ddos_tcp4_df,
    tcp_ip_ddos_udp1_df, tcp_ip_ddos_udp2_df, tcp_ip_ddos_udp3_df, tcp_ip_ddos_udp4_df, tcp_ip_ddos_udp5_df, tcp_ip_ddos_udp6_df, tcp_ip_ddos_udp7_df, tcp_ip_ddos_udp8_df
]
ddos_df = pd.concat(list_ddos_dfs, ignore_index = True)

list_dos_dfs = [
    tcp_ip_dos_icmp1_df, tcp_ip_dos_icmp2_df, tcp_ip_dos_icmp3_df, tcp_ip_dos_icmp4_df,
    tcp_ip_dos_syn1_df, tcp_ip_dos_syn2_df, tcp_ip_dos_syn3_df, tcp_ip_dos_syn4_df,
    tcp_ip_dos_tcp1_df, tcp_ip_dos_tcp2_df, tcp_ip_dos_tcp3_df, tcp_ip_dos_tcp4_df,
    tcp_ip_dos_udp1_df, tcp_ip_dos_udp2_df, tcp_ip_dos_udp3_df, tcp_ip_dos_udp4_df
]
dos_df = pd.concat(list_dos_dfs, ignore_index = True)

df_atack_category = pd.concat([
    benign_df.assign(Label = "Benign"),
    arp_spoofing_df.assign(Label = "Spoofing"),
    mqtt_df.assign(Label = 'MQTT_Attack'),
    recon_df.assign(Label = 'Reconnaissance'),
    ddos_df.assign(Label = 'DDoS'),
    dos_df.assign(Label = 'DoS')
], ignore_index = True)

In [ ]:
df_atack_category

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance,Label
0,28.28,6,61.96,19.761694,0.0,0.0,0.0,0.43,0.87,0.0,...,10850,42,929,108.500000,137.604946,108.500000,0.050603,100,18935.121212,Benign
1,31.28,6,65.91,16.671029,0.0,0.0,0.0,0.49,0.97,0.0,...,9061,66,929,90.610000,88.637258,90.610000,0.059987,100,7856.563535,Benign
2,30.44,6,72.21,18.039151,0.0,0.0,0.0,0.45,0.95,0.0,...,9247,60,930,92.470000,90.598064,92.470000,0.055435,100,8208.009192,Benign
3,31.76,6,63.37,99.573130,0.0,0.0,0.0,0.60,0.99,0.0,...,7186,66,217,71.860000,17.708082,71.860000,0.014613,100,313.576162,Benign
4,30.92,6,67.06,33.374416,0.0,0.0,0.0,0.41,0.96,0.0,...,8819,60,929,88.190000,89.906090,88.190000,0.029963,100,8083.104949,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6987385,8.00,17,64.00,30845.006619,0.0,0.0,0.0,0.00,0.00,0.0,...,6164,60,224,61.640000,16.400000,61.640000,0.000032,100,268.960000,DoS
6987386,8.00,17,64.00,29770.061750,0.0,0.0,0.0,0.00,0.00,0.0,...,6052,60,112,60.520000,5.200000,60.520000,0.000034,100,27.040000,DoS
6987387,8.00,17,64.00,29683.680113,0.0,0.0,0.0,0.00,0.00,0.0,...,6041,60,101,60.410000,4.100000,60.410000,0.000034,100,16.810000,DoS
6987388,8.00,17,64.00,37216.539485,0.0,0.0,0.0,0.00,0.00,0.0,...,17948,60,1252,179.480000,359.314119,179.480000,0.000027,100,129106.635960,DoS
6987389,8.00,17,64.00,26935.125025,0.0,0.0,0.0,0.00,0.00,0.0,...,35560,60,1252,370.416667,525.869539,370.416667,0.000037,96,276538.771930,DoS

In [ ]:
df_atack_category['Label'].value_counts()

Label
DDoS              4779859
DoS               1805529
MQTT_Attack        262938
Reconnaissance     103726
Benign              19291
Spoofing            16047
Name: count, dtype: int64

In [ ]:
# Pré-processamento direto no DF
df_atack_category.columns = df_atack_category.columns.str.replace(' ', '_', regex = False)
df_content = df_atack_category.select_dtypes(include = np.number).columns
df_atack_category[df_content] = df_atack_category[df_content].replace([np.inf, -np.inf], np.finfo(np.float32).max)
df_atack_category[df_content] = df_atack_category[df_content].fillna(0)
df_atack_category.columns

# Garante índice único
df_atack_category = df_atack_category.reset_index(drop = True)

def balanced_df(df, n_per_class, file_name):
  index_to_remove = []
  df_list = []

  for label in df['Label'].unique():
    group = df[df['Label'] == label]
    n_safe = min(len(group), n_per_class)

    if n_safe < n_per_class:
      print(f"Aviso: Classe {label} só tem {n_safe} linhas restantes.")

    sample = group.sample(n = n_safe, random_state = 42)
    df_list.append(sample)
    index_to_remove.extend(sample.index)

  df_final = pd.concat(df_list, ignore_index = True)
  df_final = shuffle(df_final, random_state = 42)
  df_final.to_csv(file_name, index = False)
  files.download(file_name)

  df = df.drop(index_to_remove)

  return df

def unbalanced(df, n, file_name):
  sample = df.sample(n = n, random_state = 42)
  sample.to_csv(file_name, index = False)
  files.download(file_name)
  df = df.drop(sample.index)
  return df

In [ ]:
# Treino
balanced_df_atack_category = balanced_df(df_atack_category, 8000, "balanced_df_atack_category.csv")

# Testes finais
test_1_balanced = unbalanced(df_atack_category, 2000, "test_1_balanced.csv")
test_2_balanced = unbalanced(df_atack_category, 2000, "test_2_balanced.csv")
test_3_unbalanced = unbalanced(df_atack_category, 6000, "test_3_unbalanced.csv")
test_4_unbalanced = unbalanced(df_atack_category, 6000, "test_4_unbalanced.csv")
test_5_unbalanced = unbalanced(df_atack_category, 6000, "test_5_unbalanced.csv")

## Fazendo a mesma coisa mas para o dataset de teste

In [ ]:
path = "/content/drive/My Drive/TCC/Dataset validação"
if os.path.isdir(path):
  print("\nConteúdo da pasta:\n")
  !ls "{path}"

Conteúdo da pasta:

ARP_Spoofing_test.pcap.csv	       TCP_IP-DDoS-ICMP1_test.pcap.csv
Benign_test.pcap.csv		       TCP_IP-DDoS-ICMP2_test.pcap.csv
MQTT-DDoS-Connect_Flood_test.pcap.csv  TCP_IP-DDoS-SYN_test.pcap.csv
MQTT-DDoS-Publish_Flood_test.pcap.csv  TCP_IP-DDoS-TCP_test.pcap.csv
MQTT-DoS-Connect_Flood_test.pcap.csv   TCP_IP-DDoS-UDP1_test.pcap.csv
MQTT-DoS-Publish_Flood_test.pcap.csv   TCP_IP-DDoS-UDP2_test.pcap.csv
MQTT-Malformed_Data_test.pcap.csv      TCP_IP-DoS-ICMP_test.pcap.csv
Recon-OS_Scan_test.pcap.csv	       TCP_IP-DoS-SYN_test.pcap.csv
Recon-Ping_Sweep_test.pcap.csv	       TCP_IP-DoS-TCP_test.pcap.csv
Recon-Port_Scan_test.pcap.csv	       TCP_IP-DoS-UDP_test.pcap.csv
Recon-VulScan_test.pcap.csv

In [ ]:
# --- Tráfego Benigno ---
benign_test_df = pd.read_csv(f"{path}/Benign_test.pcap.csv")
# --- Ataques ARP ---
arp_spoofing_test_df = pd.read_csv(f"{path}/ARP_Spoofing_test.pcap.csv")
# --- Ataques MQTT ---
mqtt_ddos_connect_flood_test_df = pd.read_csv(f"{path}/MQTT-DDoS-Connect_Flood_test.pcap.csv")
mqtt_ddos_publish_flood_test_df = pd.read_csv(f"{path}/MQTT-DDoS-Publish_Flood_test.pcap.csv")
mqtt_dos_connect_flood_test_df = pd.read_csv(f"{path}/MQTT-DoS-Connect_Flood_test.pcap.csv")
mqtt_dos_publish_flood_test_df = pd.read_csv(f"{path}/MQTT-DoS-Publish_Flood_test.pcap.csv")
mqtt_malformed_data_test_df = pd.read_csv(f"{path}/MQTT-Malformed_Data_test.pcap.csv")
# --- Ataques de Reconhecimento (Recon) ---
recon_os_scan_test_df = pd.read_csv(f"{path}/Recon-OS_Scan_test.pcap.csv")
recon_ping_sweep_test_df = pd.read_csv(f"{path}/Recon-Ping_Sweep_test.pcap.csv")
recon_port_scan_test_df = pd.read_csv(f"{path}/Recon-Port_Scan_test.pcap.csv")
recon_vulscan_test_df = pd.read_csv(f"{path}/Recon-VulScan_test.pcap.csv")
# --- Ataques DDoS ---
ddos_icmp1_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP1_test.pcap.csv")
ddos_icmp2_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-ICMP2_test.pcap.csv")
ddos_syn_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-SYN_test.pcap.csv")
ddos_tcp_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-TCP_test.pcap.csv")
ddos_udp1_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP1_test.pcap.csv")
ddos_udp2_test_df = pd.read_csv(f"{path}/TCP_IP-DDoS-UDP2_test.pcap.csv")
# --- Ataques DoS ---
dos_icmp_test_df = pd.read_csv(f"{path}/TCP_IP-DoS-ICMP_test.pcap.csv")
dos_syn_test_df = pd.read_csv(f"{path}/TCP_IP-DoS-SYN_test.pcap.csv")
dos_tcp_test_df = pd.read_csv(f"{path}/TCP_IP-DoS-TCP_test.pcap.csv")
dos_udp_test_df = pd.read_csv(f"{path}/TCP_IP-DoS-UDP_test.pcap.csv")

list_mqtt_test_dfs = [
    mqtt_ddos_connect_flood_test_df, mqtt_ddos_publish_flood_test_df,
    mqtt_dos_connect_flood_test_df, mqtt_dos_publish_flood_test_df,
    mqtt_malformed_data_test_df
]
mqtt_test_df = pd.concat(list_mqtt_test_dfs, ignore_index = True)

list_recon_test_dfs = [
    recon_os_scan_test_df, recon_ping_sweep_test_df,
    recon_port_scan_test_df, recon_vulscan_test_df
]
recon_test_df = pd.concat(list_recon_test_dfs, ignore_index = True)

list_ddos_test_dfs = [
    ddos_icmp1_test_df, ddos_icmp2_test_df,
    ddos_syn_test_df, ddos_tcp_test_df,
    ddos_udp1_test_df, ddos_udp2_test_df
]
ddos_test_df = pd.concat(list_ddos_test_dfs, ignore_index = True)

list_dos_test_dfs = [
    dos_icmp_test_df, dos_syn_test_df,
    dos_tcp_test_df, dos_udp_test_df
]
dos_test_df = pd.concat(list_dos_test_dfs, ignore_index = True)

df_atack_category_test = pd.concat([
    benign_test_df.assign(Label="Benign"),
    arp_spoofing_test_df.assign(Label="Spoofing"),
    mqtt_test_df.assign(Label='MQTT_Attack'),
    recon_test_df.assign(Label='Reconnaissance'),
    ddos_test_df.assign(Label='DDoS'),
    dos_test_df.assign(Label='DoS')
], ignore_index = True)

# Pré-processamento direto no DF
df_atack_category_test.columns = df_atack_category_test.columns.str.replace(' ', '_', regex = False)
df_content = df_atack_category_test.select_dtypes(include=np.number).columns
df_atack_category_test[df_content] = df_atack_category_test[df_content].replace([np.inf, -np.inf], np.finfo(np.float32).max)
df_atack_category_test[df_content] = df_atack_category_test[df_content].fillna(0)
df_atack_category_test

# Crio 5 datasets (3 balanceados e 2 não balanceados)
size = 24000
n_balanced = 3
n_unbalanced = 2
n_per_class = 4000
base_seed = 42
base_filename = "test_"
df_source = df_atack_category_test

def create_balanced_dataset(df, n_per_class, seed):
  df_list = []
  for label in df['Label'].unique():
    df_list.append(
        df[df['Label'] == label].sample(n = n_per_class, random_state = seed, replace = False)
    )
  balanced_df = pd.concat(df_list, ignore_index = True)
  return shuffle(balanced_df, random_state = seed)

def create_unbalanced_dataset(df, n_total, seed):
  return df.sample(n = n_total, random_state = seed, replace = False)

for i in range(n_balanced + n_unbalanced):
  seed = base_seed + i
  df_result = None

  if i < n_balanced:
    df_result = create_balanced_dataset(df_source, n_per_class, seed)
    type_str = "balanced"

  else:
    df_result = create_unbalanced_dataset(df_source, size, seed)
    type_str = "unbalanced"

  file_name = f"{base_filename}{i+1}_{type_str}.csv"
  df_result.to_csv(file_name, index = False)
  files.download(file_name)